    ALTER TABLE [TEST_DEMO] ADD [TS] varchar(64)   NULL
    GO
    ALTER TABLE [TEST_DEMO] ADD [CREATE_TIME] varchar(64)   NULL
    GO
    ALTER TABLE [TEST_DEMO] ADD [CREATE_USER] varchar(64)   NULL
    GO
    ALTER TABLE [TEST_DEMO] ADD [LAST_MODIFIED] varchar(64)   NULL
    GO
    ALTER TABLE [TEST_DEMO] ADD [LAST_MODIFY_USER] varchar(64)   NULL
    GO
    ALTER TABLE [TEST_DEMO] ADD [DR] int NULL
    GO


